apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
  namespace: aceest
spec:
  replicas: 2
  selector:
    matchLabels: { app: aceest, track: green }
  template:
    metadata:
      labels: { app: aceest, track: green }
    spec:
      containers:
      - name: web
        image: 2024ht66001/aceest-fitness:v1.3.0
        ports: [{containerPort: 5000}]
