apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-blue
  namespace: aceest
spec:
  replicas: 2
  selector:
    matchLabels: { app: aceest, track: blue }
  template:
    metadata:
      labels: { app: aceest, track: blue }
    spec:
      containers:
      - name: web
        image: 2024ht66001/aceest-fitness:v1.2.0
        ports: [{containerPort: 5000}]
